### ISSUE TITLE
aleph-message does not expose a __version__ value

### ISSUE THREAD

**Issue by odesenfans** [aleph-im/aleph-message#73]
```
aleph_message.__version__
Traceback (most recent call last):
  File "/home/odesenfans/pycharm-2021.3.1/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
AttributeError: module 'aleph_message' has no attribute '__version__'
```

**Comment by hoh** [comment]
When does this happen ?

**Comment by odesenfans** [comment]
When installing aleph-message in a clean virtualenv. I just reproduced it using the following steps:

```
python -m virtualenv venv
source venv/bin/activate
pip install aleph-message==0.4.0

python
>>> import aleph_message
>>> print(aleph_message.__version__)
```

results in

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aleph_message' has no attribute `__version__`
